import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Menu from "@/components/Menu";

const calora = localFont({
    src: [
        {
            path: '../assets/fonts/calora-font/calora.otf',
            style: 'normal',
        }
    ],
    variable: "--font-calora-normal",
})

const gotham = localFont({
    src: [
        {
            path: '../assets/fonts/gotham-fonts/Gotham-Medium.otf',
            weight: '300',
            style: 'medium',
        },
        {
            path: '../assets/fonts/gotham-fonts/Gotham-Book.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../assets/fonts/gotham-fonts/Gotham-Bold.otf',
            weight: '700',
            style: 'bold',
        },
        {
            path: '../assets/fonts/gotham-fonts/Gotham-Thin.otf',
            weight: '500',
            style: 'thin',
        }
    ],
    variable: "--font-gotham",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${gotham.variable} ${calora.variable} antialiased`}
        >
        <Menu/>
        {children}
        </body>
        </html>
    );
}
