/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Artists = {
  _id: string;
  _type: "artists";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  pressKit?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  links?: Array<{
    platform?:
      | "Spotify"
      | "SoundCloud"
      | "Beatport"
      | "Bandcamp"
      | "Instagram"
      | "TikTok"
      | "FaceBook"
      | "Youtube"
      | "WebSite";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Partners = {
  _id: string;
  _type: "partners";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  partner?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
};

export type Releases = {
  _id: string;
  _type: "releases";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  artist?: string;
  catalog?: number;
  releaseDate?: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<{
    beatport?: string;
    soundcloud?: string;
    spotify?: string;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Artists
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Partners
  | Releases
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../frontend/sanity/queries.ts
// Variable: landingReleaseQuery
// Query: *[_type == "releases"] | order(_createdAt desc) [0...4]{        _id, catalog, cover, title, artist, links, releaseDate    }
export type LandingReleaseQueryResult = Array<{
  _id: string;
  catalog: number | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  title: string | null;
  artist: string | null;
  links: Array<{
    beatport?: string;
    soundcloud?: string;
    spotify?: string;
    _key: string;
  }> | null;
  releaseDate: string | null;
}>;

// Source: ../frontend/sanity/queries.ts
// Variable: releaseQuery
// Query: *[_type == "releases"] | order(_createdAt desc){        _id, catalog, cover, title, artist, links, releaseDate    }
export type ReleaseQueryResult = Array<{
  _id: string;
  catalog: number | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  title: string | null;
  artist: string | null;
  links: Array<{
    beatport?: string;
    soundcloud?: string;
    spotify?: string;
    _key: string;
  }> | null;
  releaseDate: string | null;
}>;

// Source: ../frontend/sanity/queries.ts
// Variable: partnerQuery
// Query: *[_type == "partners"]{        _id, partner, logo, link    }
export type PartnerQueryResult = Array<{
  _id: string;
  partner: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  link: string | null;
}>;

// Source: ../frontend/sanity/queries.ts
// Variable: artistQuery
// Query: *[_type == "artists"]{      _id,       name,       slug,       profileImage,      bio,       pressKit,      links    }
export type ArtistQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  pressKit: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  } | null;
  links: Array<{
    platform?:
      | "Bandcamp"
      | "Beatport"
      | "FaceBook"
      | "Instagram"
      | "SoundCloud"
      | "Spotify"
      | "TikTok"
      | "WebSite"
      | "Youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
}>;

// Source: ../frontend/sanity/queries.ts
// Variable: artistBySlugQuery
// Query: *[_type == "artists" && slug.current == $slug][0]{    _id,    name,    slug,    profileImage,    bio,    "pressKit": pressKit.asset->url,     links  }
export type ArtistBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  pressKit: string | null;
  links: Array<{
    platform?:
      | "Bandcamp"
      | "Beatport"
      | "FaceBook"
      | "Instagram"
      | "SoundCloud"
      | "Spotify"
      | "TikTok"
      | "WebSite"
      | "Youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n    *[_type == "releases"] | order(_createdAt desc) [0...4]{\n        _id, catalog, cover, title, artist, links, releaseDate\n    }\n ': LandingReleaseQueryResult;
    '\n    *[_type == "releases"] | order(_createdAt desc){\n        _id, catalog, cover, title, artist, links, releaseDate\n    }\n ': ReleaseQueryResult;
    '\n    *[_type == "partners"]{\n        _id, partner, logo, link\n    }\n': PartnerQueryResult;
    '\n    *[_type == "artists"]{\n      _id, \n      name, \n      slug, \n      profileImage,\n      bio, \n      pressKit,\n      links\n    }\n': ArtistQueryResult;
    '\n  *[_type == "artists" && slug.current == $slug][0]{\n    _id,\n    name,\n    slug,\n    profileImage,\n    bio,\n    "pressKit": pressKit.asset->url, \n    links\n  }\n': ArtistBySlugQueryResult;
  }
}
